#-------------------------------
# General Site Settings

title: Mitch McClellan | Painterly Code
owner: Mitch McClellan
description: >- # this means to ignore newlines until "baseurl:"
  I'm Mitch McClellan, I'm a Technical Artist and VFX Artist, and this is my blog and
  portfolio website. Most of the articles cover topics related to gamedev, VFX, and shaders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mitjmcc.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Mitch McClellan
author-avatar: 21.jpg


#-------------------------------
# Contact links
mastodon:   https://mastodon.gamedev.place/@iamhand
twitter:    https://twitter.com/MitchJMcClellan # Add your Twitter handle
instagram:  https://www.instagram.com/mitchjmcc/ # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
newsletter: false
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Robot block
robots_txt: >-
  User-agent: *
  User-agent: AdsBot-Google
  User-agent: Amazonbot
  User-agent: anthropic-ai
  User-agent: Applebot
  User-agent: Applebot-Extended
  User-agent: AwarioRssBot
  User-agent: AwarioSmartBot
  User-agent: Bytespider
  User-agent: CCBot
  User-agent: ChatGPT-User
  User-agent: ClaudeBot
  User-agent: Claude-Web
  User-agent: cohere-ai
  User-agent: DataForSeoBot
  User-agent: Diffbot
  User-agent: FacebookBot
  User-agent: FriendlyCrawler
  User-agent: Google-Extended
  User-agent: GoogleOther
  User-agent: GPTBot
  User-agent: img2dataset
  User-agent: ImagesiftBot
  User-agent: magpie-crawler
  User-agent: Meltwater
  User-agent: omgili
  User-agent: omgilibot
  User-agent: peer39_crawler
  User-agent: peer39_crawler/1.0
  User-agent: PerplexityBot
  User-agent: PiplBot
  User-agent: scoop.it
  User-agent: Seekr
  User-agent: YouBot
  Disallow: /

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-email-protect # use when making an email link
#  - jekyll-pdf-embed use to embed resume

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  auto_id_stripping: true


#-------------------------------
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
